<?php


namespace App\Providers;


use baofeng\Demo\ServiceProviders\ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    protected $namespace = 'App\Controllers';

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $this->map();
    }

    public function map()
    {
        $this->mapWebRoutes();
        //
    }

    protected function mapWebRoutes()
    {
        require_once base_path("/route/web.php");
    }
}